version: '3.7'

services:
    api:
        build: .
        container_name: apicrm
        command: "python manage.py runserver -h 0.0.0.0"
        volumes:
            - ./utils:/usr/src/app/utils
            - ./models:/usr/src/app/models
            - ./controllers:/usr/src/app/controllers
            - ./app.py:/usr/src/app/app.py
            - ./config.py:/usr/src/app/config.py
            - ./manage.py:/usr/src/app/manage.py
        ports:
            - 5000:5000
        env_file:
            - .env
        depends_on:
            - apidb
        networks:
            dev:
    
    apidb:
        image: postgres:12-alpine
        container_name: crmdb
        expose:
            - 5432
        env_file:
            - .env
        networks:
            dev:

volumes:
    postgres_data:

networks:
    dev: